---
- hosts: wordpress
  become: yes
  remote_user: root
  vars:
    wp_mysql_db: wordpress
    wp_mysql_user: wpuser
    wp_mysql_password: password
  roles: 
    - {role: wplamp/php_config, tags: ['php_config']}
    - {role: wplamp/apache_install, tags: ['apache_install']}
    - {role: wplamp/mysql_install, tags: ['mysql_install']}
    - {role: wplamp/wordpress, tags: ['wordpress']}