---
php_ubuntu_packages:
  - php
  - libapache2-mod-php
  - php-cli
  - php-common
  - php-gd
  - php-json
  - php-curl
  - php-mbstring
  - php-mysqlnd
  - php-xml
  - php-xmlrpc
  - php-soap
  - php-intl
  - php-zip
  - php-opcache
  
php_centos7_packages:
  - php
  - php-cli
  - php-common
  - php-mcrypt
  - php-gd
  - php-json
  - php-curl
  - php-mbstring
  - php-mysqlnd
  - php-xml
  - php-xmlrpc
  - php-opcache