---
# Create db for wordpress
- name: Ubuntu create db wordpress
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{wp_mysql_db}}"
    encoding: latin1
    collation: latin1_general_ci

# Create user for wordpress
- name: Ubuntu create user wordpress
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{wp_mysql_user}}"
    host: "%"
    password: "{{wp_mysql_password}}"
    priv: "*.*:ALL"