---
# install task 
- include_tasks: php_install_centos7.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include_tasks: php_install_ubuntu18.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'