---
# tasks file for apache_install
- name : install apache ubuntu
  apt:
    name: "{{ apache_packages }}"
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name : install apache centos
  yum:
    name: "{{ httpd_packages }}"
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Start httpd service
  service: 
    name: "{{ httpd_name_service }}"
    enabled: true
    state: started
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'